### ISSUE TITLE
what is "packetIds.json and proto/"

### ISSUE THREAD

**Issue by MoonShadowIllusion** [Crepe-Inc/Iridium#2]
I'm a novice in computer

**Comment by nitrog0d** [comment]
they're created using this tool: https://github.com/nitrog0d/ProtoDumper

**Comment by Winter-is-comingXK** [comment]
> 

PS C:\Users\xuke\Source\Repos\ProtoDumper\bin\Release> .\ProtoDumper.exe -output-path="." --assembly-path="C:\Users\xuke\source\repos\Il2CppDumper-GenshinImpact\Il2CppDumper\bin\Release\net472\DummyDll\Assembly-CSharp.dll" --export-type=typescript
Unrecognized option -output-path=., use -h for help.
Parsing protos...
Proto parsing done!
Old protos found! Deleting.
Dumping to folder: C:\Users\xuke\source\repos\ProtoDumper\bin\Release\Output\
Using export type "TypeScript".

未经处理的异常:  System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 ProtoDumper.Outputs.BaseDumper.Dump(String fileExtension) 位置 C:\Users\xuke\Source\Repos\ProtoDumper\Outputs\BaseDumper.cs:行号 130
   在 ProtoDumper.Program.Main(String[] args) 位置 C:\Users\xuke\Source\Repos\ProtoDumper\Program.cs:行号 108

**Comment by Winter-is-comingXK** [comment]
> they're created using this tool: https://github.com/nitrog0d/ProtoDumper

PS C:\Users\xuke\Source\Repos\ProtoDumper\bin\Release> .\ProtoDumper.exe -output-path=".\" --assembly-path="C:\Users\xuke\source\repos\Il2CppDumper-GenshinImpact\Il2CppDumper\bin\Release\net472\DummyDll\Assembly-CSharp.dll"
Unrecognized option -output-path=.\, use -h for help.
Parsing protos...
Proto parsing done!
Old protos found! Deleting.
Dumping to folder: C:\Users\xuke\source\repos\ProtoDumper\bin\Release\Output\
Using export type "Proto".

未经处理的异常:  System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 ProtoDumper.Outputs.BaseDumper.Dump(String fileExtension) 位置 C:\Users\xuke\Source\Repos\ProtoDumper\Outputs\BaseDumper.cs:行号 130
   在 ProtoDumper.Program.Main(String[] args) 位置 C:\Users\xuke\Source\Repos\ProtoDumper\Program.cs:行号 113
