### ISSUE TITLE
client startup error

### ISSUE THREAD

**Issue by nasocksok** [Crepe-Inc/Iridium#3]
I can't log into the game, I run everything according to the instructions, but I can't configure the hosts, please help, I tried without a fiddler, nothing works.
Can you tell us more details please)

screenshots error

https://prnt.sc/VK_V6GZDv4nV
https://prnt.sc/_KiopcnOq4wA
https://prnt.sc/INAXjgzBKSuO

**Comment by nitrog0d** [comment]
skill issue

**Comment by nasocksok** [comment]
Please help me solve this

**Comment by nitrog0d** [comment]
no

**Comment by nasocksok** [comment]
then what's the point of creating a project and not helping people?
hahahahaha

**Comment by Taiga74164** [comment]
skill issue

**Comment by nitrog0d** [comment]
https://github.com/Crepe-Inc/Iridium/commit/f6ad368545bbfc5a9a1169a2726c6cd715cb00ea

**Comment by memetrollsXD** [comment]
https://docs.rackspace.com/support/how-to/modify-your-hosts-file/

Pancake fiddler is no longer supported.

**Comment by Algoinde** [comment]
@nasocksok first, you need to determine which hosts exactly to redirect, as they will be used during the initial HTTP phase.
Then you will need to get (your own) IDs of packets, which were broken with the latest version of the client. It will probably take a while.
